### ISSUE TITLE
Hello, i dont know how to make this work.

### ISSUE THREAD

**Issue by xxdeathsteel41** [sALTaccount/PromptInspectorBot#10]
So, i been trying for the last 4 hours to try and figure out how to use this. I followed multiple tutorials on youtube on how  to make a discord bot but none really helped with compiling the files with the bot. I also read the READ ME file and followed every step and I run the  python3 PromptInspector.py. But i get an error of  

(import toml
ModuleNotFoundError: No module named 'toml')

I also have a problem with PromptInspector.py which says:

"gzip" is not defined.

I dont really know if am really clueless with what am doing or if this project doesnt work but I found no answer to my problems.

I am writing this issue hopping that someone will reach out to me and help me fix a properly working discord bot with this amazing function.

**Comment by yoinked-h** [comment]
`pip install toml`

**Comment by saltacc** [comment]
you can type the errors into google and you get solutions (the first result says to install toml with pip). [ChatGPT](https://chat.openai.com/) can also answer questions like this. Anyways this is a fairly old issue so I'm going to be closing it.
