### ISSUE TITLE
Problems with BOT_TOKEN and os.py

### ISSUE THREAD

**Issue by DrNey** [sALTaccount/PromptInspectorBot#12]
Hello, I have a problem. I did everything according to the instructions, but when it came to launching the executable file, the following error pops up:

Traceback (most recent call last):
  File "D:\SD\PromptInspectorBot-master\PromptInspector.py", line 297, in <module>
    client.run(os.environ["BOT_TOKEN"])
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'BOT_TOKEN'

If anything, I created a "bt.env" file with token in the same folder where the .py file is located, as written in the instructions. Any ideas what's wrong?

**Comment by merolaika** [comment]
@DrNey change file name bt.env to .env only. I do it and its work

**Comment by saltacc** [comment]
Just saw this and yeah, that's the issue. The instructions say nothing about "bt.env", it says ".env"
